apiVersion: v1
kind: Namespace
metadata:
  name: sms
  labels:
    app.kubernetes.io/part-of: student-management-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sms-ksa
  namespace: sms
  annotations:
    # Replace PROJECT_ID with your GCP project ID
    iam.gke.io/gcp-service-account: sms-workload@PROJECT_ID.iam.gserviceaccount.com
